subroutine WRITE_MDP(md_time,dark_or_light,c11)

implicit none

integer         :: md_time

integer              :: dark_or_light

character(len=4)  :: c11

if(c11 == 'cate') then

 open(unit=432,file='fullmd_sol.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(1x,a12,i7)') 'nsteps  		 =',md_time
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein'  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein non-protein'   
 write(432,*) 'tau_t	        = 0   0.1 ' 
 write(432,*) 'ref_t		 = 300 300 ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)


 open(unit=432,file='relax.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(a28)') 'nsteps  		 = 100000'
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein  '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein non-protein'   
 write(432,*) 'tau_t	        = 0   0.1 ' 
 write(432,*) 'ref_t		 = 300 300 ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=4323,file='fullmd_solequil.mdp')

 write(4323,*) 'title                    = MD simulation LOV2-Jalpha'

 write(4323,*) ';Preprocessor'
 write(4323,*) 'cpp			 = /lib/cpp'
 write(4323,*) ';Directories to include in the topology format'
 write(4323,*) 'include 		 = -I../top'
 write(4323,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(4323,*) 'integrator		 = md'
 write(4323,*) ';Total simulation time: 100 ps'
 write(4323,*) ':time step in femtoseconds'  
 write(4323,*) 'dt			 = 0.0005'
 write(4323,*) ';number of steps'
 write(4323,*) 'nsteps  		 = 1500'
 write(4323,*) ';frequency to write coordinates to output trajectory file'
 write(4323,*) 'nstxout 		 = 3000'
 write(4323,*) ';frequency to write velocities to output trajectory file'
 write(4323,*) 'nstvout 		 = 3000'
 write(4323,*) ';frequency to write energies to log file'
 write(4323,*) 'nstlog  		 = 3000'
 write(4323,*) ';frequency to write energies to energy file'
 write(4323,*) 'nstenergy		 = 200'
 write(4323,*) ';frequency to write coordinates to xtc trajectory' 
 write(4323,*) 'nstxtcout		 = 3000'
 write(4323,*) ';group(s) to write to xtc trajectory'
 write(4323,*) 'xtc_grps		 = protein'  
 write(4323,*) 'group(s) to write to energy file' 
 write(4323,*) 'energygrps		 = protein '
 write(4323,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(4323,*) ';when using twin-range cut-offs).' 
 write(4323,*) 'nstlist 		 = 10'
 write(4323,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(4323,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(4323,*) 'ns_type 		 = grid'
 write(4323,*) ';cut-off distance for the short-range neighbor list'
 write(4323,*) 'rlist		 = 1.4 '
 write(4323,*) ';treatment of electrostatic interactions'
 write(4323,*) 'coulombtype		 = pme'
 write(4323,*) 'pme_order            = 4'
 write(4323,*) 'fourierspacing       = 0.12' 
 write(4323,*) 'rcoulomb		 = 1.4' 
 write(4323,*) ';treatment of van der waals interactions'
 write(4323,*) 'rvdw			 = 1.4'
 write(4323,*) '; Periodic boudary conditions in all the directions' 
 write(4323,*) 'pbc                      = xyz'
 write(4323,*) ';Temperature coupling'
 write(4323,*) 'tcoupl  		 = berendsen'
 write(4323,*) 'tc-grps 		 = protein non-protein'   
 write(4323,*) 'tau_t	        = 0    0.1 ' 
 write(4323,*) 'ref_t		 = 300 300 ' 
 write(4323,*) ';Pressure coupling'
 write(4323,*) 'Pcoupl  		 = No'
 write(4323,*) 'Pcoupltype           = isotropic'
 write(4323,*) 'tau_p		 = 1.0'
 write(4323,*) 'compressibility 	 = 4.5e-5'
 write(4323,*) 'ref_p		 = 1.0'
 write(4323,*) ';Velocity generation'
 write(4323,*) 'gen_vel 		 = yes' 
 write(4323,*) 'gen_temp		 = 300'
 write(4323,*) 'gen_seed		 = 173529'
 write(4323,*) ';Constrain all bonds'
 write(4323,*) 'constraints		 = none'
 write(4323,*) ';freezegrps'
 write(4323,*) 'freezegrps               = protein '
 write(4323,*) 'freezedim                = Y Y Y   '

 close(unit=4323)

endif

if(dark_or_light == 1 .and. c11 == 'phot' ) then

 open(unit=432,file='fullmd_sol.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(1x,a12,i7)') 'nsteps  		 =',md_time
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein FMNP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol FMNP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  FMNP SOL '   
 write(432,*) 'tau_t	        = 0   0    0.1 ' 
 write(432,*) 'ref_t		 = 300 300 300 ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)


 open(unit=432,file='relax.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(a28)') 'nsteps  		 = 300000'
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein FMNP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol FMNP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  FMNP SOL '   
 write(432,*) 'tau_t	        = 0   0    0.1 ' 
 write(432,*) 'ref_t		 = 300 300 300 ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=4323,file='fullmd_solequil.mdp')

 write(4323,*) 'title                    = MD simulation LOV2-Jalpha'

 write(4323,*) ';Preprocessor'
 write(4323,*) 'cpp			 = /lib/cpp'
 write(4323,*) ';Directories to include in the topology format'
 write(4323,*) 'include 		 = -I../top'
 write(4323,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(4323,*) 'integrator		 = md'
 write(4323,*) ';Total simulation time: 100 ps'
 write(4323,*) ':time step in femtoseconds'  
 write(4323,*) 'dt			 = 0.0005'
 write(4323,*) ';number of steps'
 write(4323,*) 'nsteps  		 = 2000'
 write(4323,*) ';frequency to write coordinates to output trajectory file'
 write(4323,*) 'nstxout 		 = 3000'
 write(4323,*) ';frequency to write velocities to output trajectory file'
 write(4323,*) 'nstvout 		 = 3000'
 write(4323,*) ';frequency to write energies to log file'
 write(4323,*) 'nstlog  		 = 3000'
 write(4323,*) ';frequency to write energies to energy file'
 write(4323,*) 'nstenergy		 = 200'
 write(4323,*) ';frequency to write coordinates to xtc trajectory' 
 write(4323,*) 'nstxtcout		 = 3000'
 write(4323,*) ';group(s) to write to xtc trajectory'
 write(4323,*) 'xtc_grps		 = protein FMNP '  
 write(4323,*) 'group(s) to write to energy file' 
 write(4323,*) 'energygrps		 = protein sol FMNP '
 write(4323,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(4323,*) ';when using twin-range cut-offs).' 
 write(4323,*) 'nstlist 		 = 10'
 write(4323,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(4323,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(4323,*) 'ns_type 		 = grid'
 write(4323,*) ';cut-off distance for the short-range neighbor list'
 write(4323,*) 'rlist		 = 1.4 '
 write(4323,*) ';treatment of electrostatic interactions'
 write(4323,*) 'coulombtype		 = pme'
 write(4323,*) 'pme_order            = 4'
 write(4323,*) 'fourierspacing       = 0.12' 
 write(4323,*) 'rcoulomb		 = 1.4' 
 write(4323,*) ';treatment of van der waals interactions'
 write(4323,*) 'rvdw			 = 1.4'
 write(4323,*) '; Periodic boudary conditions in all the directions' 
 write(4323,*) 'pbc                      = xyz'
 write(4323,*) ';Temperature coupling'
 write(4323,*) 'tcoupl  		 = berendsen'
 write(4323,*) 'tc-grps 		 = protein  FMNP SOL '   
 write(4323,*) 'tau_t	        = 0   0    0.1 ' 
 write(4323,*) 'ref_t		 = 300 300 100 ' 
 write(4323,*) ';Pressure coupling'
 write(4323,*) 'Pcoupl  		 = No'
 write(4323,*) 'Pcoupltype           = isotropic'
 write(4323,*) 'tau_p		 = 1.0'
 write(4323,*) 'compressibility 	 = 4.5e-5'
 write(4323,*) 'ref_p		 = 1.0'
 write(4323,*) ';Velocity generation'
 write(4323,*) 'gen_vel 		 = yes' 
 write(4323,*) 'gen_temp		 = 300'
 write(4323,*) 'gen_seed		 = 173529'
 write(4323,*) ';Constrain all bonds'
 write(4323,*) 'constraints		 = none'
 write(4323,*) ';freezegrps'
 write(4323,*) 'freezegrps               = protein FMNP '
 write(4323,*) 'freezedim                = Y Y Y  Y Y Y '

 close(unit=4323)

endif


if(dark_or_light == 0 .and. c11 == 'phot' ) then

 open(unit=432,file='fullmd_sol.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(1x,a12,i7)') 'nsteps  		 =',md_time
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein CFP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol CFP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  CFP SOL   '   
 write(432,*) 'tau_t	        = 0   0    0.1  ' 
 write(432,*) 'ref_t		 = 300 300 300  ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=432,file='relax.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(a28)') 'nsteps  		 = 300000'
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein CFP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol CFP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  CFP SOL '   
 write(432,*) 'tau_t	        = 0   0    0.1 ' 
 write(432,*) 'ref_t		 = 300 300 300 ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=4323,file='fullmd_solequil.mdp')

 write(4323,*) 'title                    = MD simulation LOV2-Jalpha'

 write(4323,*) ';Preprocessor'
 write(4323,*) 'cpp			 = /lib/cpp'
 write(4323,*) ';Directories to include in the topology format'
 write(4323,*) 'include 		 = -I../top'
 write(4323,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(4323,*) 'integrator		 = md'
 write(4323,*) ';Total simulation time: 100 ps'
 write(4323,*) ':time step in femtoseconds'  
 write(4323,*) 'dt			 = 0.0005'
 write(4323,*) ';number of steps'
 write(4323,*) 'nsteps  		 = 2000'
 write(4323,*) ';frequency to write coordinates to output trajectory file'
 write(4323,*) 'nstxout 		 = 3000'
 write(4323,*) ';frequency to write velocities to output trajectory file'
 write(4323,*) 'nstvout 		 = 3000'
 write(4323,*) ';frequency to write energies to log file'
 write(4323,*) 'nstlog  		 = 3000'
 write(4323,*) ';frequency to write energies to energy file'
 write(4323,*) 'nstenergy		 = 200'
 write(4323,*) ';frequency to write coordinates to xtc trajectory' 
 write(4323,*) 'nstxtcout		 = 3000'
 write(4323,*) ';group(s) to write to xtc trajectory'
 write(4323,*) 'xtc_grps		 = protein CFP '  
 write(4323,*) 'group(s) to write to energy file' 
 write(4323,*) 'energygrps		 = protein sol CFP '
 write(4323,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(4323,*) ';when using twin-range cut-offs).' 
 write(4323,*) 'nstlist 		 = 10'
 write(4323,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(4323,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(4323,*) 'ns_type 		 = grid'
 write(4323,*) ';cut-off distance for the short-range neighbor list'
 write(4323,*) 'rlist		 = 1.4 '
 write(4323,*) ';treatment of electrostatic interactions'
 write(4323,*) 'coulombtype		 = pme'
 write(4323,*) 'pme_order            = 4'
 write(4323,*) 'fourierspacing       = 0.12' 
 write(4323,*) 'rcoulomb		 = 1.4' 
 write(4323,*) ';treatment of van der waals interactions'
 write(4323,*) 'rvdw			 = 1.4'
 write(4323,*) '; Periodic boudary conditions in all the directions' 
 write(4323,*) 'pbc                      = xyz'
 write(4323,*) ';Temperature coupling'
 write(4323,*) 'tcoupl  		 = berendsen'
 write(4323,*) 'tc-grps 		 = protein  CFP SOL '   
 write(4323,*) 'tau_t	        = 0   0    0.1 ' 
 write(4323,*) 'ref_t		 = 300 300 100 ' 
 write(4323,*) ';Pressure coupling'
 write(4323,*) 'Pcoupl  		 = No'
 write(4323,*) 'Pcoupltype           = isotropic'
 write(4323,*) 'tau_p		 = 1.0'
 write(4323,*) 'compressibility 	 = 4.5e-5'
 write(4323,*) 'ref_p		 = 1.0'
 write(4323,*) ';Velocity generation'
 write(4323,*) 'gen_vel 		 = yes' 
 write(4323,*) 'gen_temp		 = 300'
 write(4323,*) 'gen_seed		 = 173529'
 write(4323,*) ';Constrain all bonds'
 write(4323,*) 'constraints		 = none'
 write(4323,*) ';freezegrps'
 write(4323,*) 'freezegrps               = protein CFP  '
 write(4323,*) 'freezedim                = Y Y Y  Y Y Y '

 close(unit=4323)

endif


if(dark_or_light == 0 .and. c11 == 'lov2' ) then

 open(unit=432,file='fullmd_sol.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(1x,a12,i7)') 'nsteps  		 =',md_time
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein CFP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol CFP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  CFP SOL NA+  '   
 write(432,*) 'tau_t	        = 0   0    0.1 0.1 ' 
 write(432,*) 'ref_t		 = 300 300 300 300 ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=432,file='relax.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(a28)') 'nsteps  		 = 300000'
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein CFP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol CFP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  CFP SOL NA+  '   
 write(432,*) 'tau_t	        = 0   0    0.1 0.1 ' 
 write(432,*) 'ref_t		 = 300 300 300 300 ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=4323,file='fullmd_solequil.mdp')

 write(4323,*) 'title                    = MD simulation LOV2-Jalpha'

 write(4323,*) ';Preprocessor'
 write(4323,*) 'cpp			 = /lib/cpp'
 write(4323,*) ';Directories to include in the topology format'
 write(4323,*) 'include 		 = -I../top'
 write(4323,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(4323,*) 'integrator		 = md'
 write(4323,*) ';Total simulation time: 100 ps'
 write(4323,*) ':time step in femtoseconds'  
 write(4323,*) 'dt			 = 0.0005'
 write(4323,*) ';number of steps'
 write(4323,*) 'nsteps  		 = 2000'
 write(4323,*) ';frequency to write coordinates to output trajectory file'
 write(4323,*) 'nstxout 		 = 3000'
 write(4323,*) ';frequency to write velocities to output trajectory file'
 write(4323,*) 'nstvout 		 = 3000'
 write(4323,*) ';frequency to write energies to log file'
 write(4323,*) 'nstlog  		 = 3000'
 write(4323,*) ';frequency to write energies to energy file'
 write(4323,*) 'nstenergy		 = 200'
 write(4323,*) ';frequency to write coordinates to xtc trajectory' 
 write(4323,*) 'nstxtcout		 = 3000'
 write(4323,*) ';group(s) to write to xtc trajectory'
 write(4323,*) 'xtc_grps		 = protein CFP '  
 write(4323,*) 'group(s) to write to energy file' 
 write(4323,*) 'energygrps		 = protein sol CFP '
 write(4323,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(4323,*) ';when using twin-range cut-offs).' 
 write(4323,*) 'nstlist 		 = 10'
 write(4323,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(4323,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(4323,*) 'ns_type 		 = grid'
 write(4323,*) ';cut-off distance for the short-range neighbor list'
 write(4323,*) 'rlist		 = 1.4 '
 write(4323,*) ';treatment of electrostatic interactions'
 write(4323,*) 'coulombtype		 = pme'
 write(4323,*) 'pme_order            = 4'
 write(4323,*) 'fourierspacing       = 0.12' 
 write(4323,*) 'rcoulomb		 = 1.4' 
 write(4323,*) ';treatment of van der waals interactions'
 write(4323,*) 'rvdw			 = 1.4'
 write(4323,*) '; Periodic boudary conditions in all the directions' 
 write(4323,*) 'pbc                      = xyz'
 write(4323,*) ';Temperature coupling'
 write(4323,*) 'tcoupl  		 = berendsen'
 write(4323,*) 'tc-grps 		 = protein  CFP SOL NA+ '   
 write(4323,*) 'tau_t	        = 0   0    0.1 0.1 ' 
 write(4323,*) 'ref_t		 = 300 300 100 100 ' 
 write(4323,*) ';Pressure coupling'
 write(4323,*) 'Pcoupl  		 = No'
 write(4323,*) 'Pcoupltype           = isotropic'
 write(4323,*) 'tau_p		 = 1.0'
 write(4323,*) 'compressibility 	 = 4.5e-5'
 write(4323,*) 'ref_p		 = 1.0'
 write(4323,*) ';Velocity generation'
 write(4323,*) 'gen_vel 		 = yes' 
 write(4323,*) 'gen_temp		 = 300'
 write(4323,*) 'gen_seed		 = 173529'
 write(4323,*) ';Constrain all bonds'
 write(4323,*) 'constraints		 = none'
 write(4323,*) ';freezegrps'
 write(4323,*) 'freezegrps               = protein CFP  '
 write(4323,*) 'freezedim                = Y Y Y  Y Y Y '

 close(unit=4323)

endif

if(dark_or_light == 1 .and. c11 == 'lov2' ) then

 open(unit=432,file='fullmd_sol.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(1x,a12,i7)') 'nsteps  		 =',md_time
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein FMNP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol FMNP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  FMNP SOL NA+ '   
 write(432,*) 'tau_t	        = 0   0    0.1 0.1 ' 
 write(432,*) 'ref_t		 = 300 300 300 300 ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)


 open(unit=432,file='relax.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(a28)') 'nsteps  		 = 300000'
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein FMNP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol FMNP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  FMNP SOL NA+ '   
 write(432,*) 'tau_t	        = 0   0    0.1 0.1 ' 
 write(432,*) 'ref_t		 = 300 300 300 300 ' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=4323,file='fullmd_solequil.mdp')

 write(4323,*) 'title                    = MD simulation LOV2-Jalpha'

 write(4323,*) ';Preprocessor'
 write(4323,*) 'cpp			 = /lib/cpp'
 write(4323,*) ';Directories to include in the topology format'
 write(4323,*) 'include 		 = -I../top'
 write(4323,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(4323,*) 'integrator		 = md'
 write(4323,*) ';Total simulation time: 100 ps'
 write(4323,*) ':time step in femtoseconds'  
 write(4323,*) 'dt			 = 0.0005'
 write(4323,*) ';number of steps'
 write(4323,*) 'nsteps  		 = 2000'
 write(4323,*) ';frequency to write coordinates to output trajectory file'
 write(4323,*) 'nstxout 		 = 3000'
 write(4323,*) ';frequency to write velocities to output trajectory file'
 write(4323,*) 'nstvout 		 = 3000'
 write(4323,*) ';frequency to write energies to log file'
 write(4323,*) 'nstlog  		 = 3000'
 write(4323,*) ';frequency to write energies to energy file'
 write(4323,*) 'nstenergy		 = 200'
 write(4323,*) ';frequency to write coordinates to xtc trajectory' 
 write(4323,*) 'nstxtcout		 = 3000'
 write(4323,*) ';group(s) to write to xtc trajectory'
 write(4323,*) 'xtc_grps		 = protein FMNP '  
 write(4323,*) 'group(s) to write to energy file' 
 write(4323,*) 'energygrps		 = protein sol FMNP '
 write(4323,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(4323,*) ';when using twin-range cut-offs).' 
 write(4323,*) 'nstlist 		 = 10'
 write(4323,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(4323,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(4323,*) 'ns_type 		 = grid'
 write(4323,*) ';cut-off distance for the short-range neighbor list'
 write(4323,*) 'rlist		 = 1.4 '
 write(4323,*) ';treatment of electrostatic interactions'
 write(4323,*) 'coulombtype		 = pme'
 write(4323,*) 'pme_order            = 4'
 write(4323,*) 'fourierspacing       = 0.12' 
 write(4323,*) 'rcoulomb		 = 1.4' 
 write(4323,*) ';treatment of van der waals interactions'
 write(4323,*) 'rvdw			 = 1.4'
 write(4323,*) '; Periodic boudary conditions in all the directions' 
 write(4323,*) 'pbc                      = xyz'
 write(4323,*) ';Temperature coupling'
 write(4323,*) 'tcoupl  		 = berendsen'
 write(4323,*) 'tc-grps 		 = protein  FMNP SOL NA+ '   
 write(4323,*) 'tau_t	        = 0   0    0.1 0.1 ' 
 write(4323,*) 'ref_t		 = 300 300 100 100 ' 
 write(4323,*) ';Pressure coupling'
 write(4323,*) 'Pcoupl  		 = No'
 write(4323,*) 'Pcoupltype           = isotropic'
 write(4323,*) 'tau_p		 = 1.0'
 write(4323,*) 'compressibility 	 = 4.5e-5'
 write(4323,*) 'ref_p		 = 1.0'
 write(4323,*) ';Velocity generation'
 write(4323,*) 'gen_vel 		 = yes' 
 write(4323,*) 'gen_temp		 = 300'
 write(4323,*) 'gen_seed		 = 173529'
 write(4323,*) ';Constrain all bonds'
 write(4323,*) 'constraints		 = none'
 write(4323,*) ';freezegrps'
 write(4323,*) 'freezegrps               = protein FMNP '
 write(4323,*) 'freezedim                = Y Y Y  Y Y Y '

 close(unit=4323)

endif

if(dark_or_light == 0 .and. c11 == 'rac1' ) then

 open(unit=432,file='fullmd_sol.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(1x,a12,i7)') 'nsteps  		 =',md_time
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein CFP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol CFP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  CFP SOL NA+ GTP '   
 write(432,*) 'tau_t	        = 0   0    0.1 0.1 0' 
 write(432,*) 'ref_t		 = 300 300 300 300 300' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=432,file='relax.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(a28)') 'nsteps  		 = 300000'
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein CFP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol CFP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  CFP SOL NA+ GTP '   
 write(432,*) 'tau_t	        = 0   0    0.1 0.1 0' 
 write(432,*) 'ref_t		 = 300 300 300 300 300' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=4323,file='fullmd_solequil.mdp')

 write(4323,*) 'title                    = MD simulation LOV2-Jalpha'

 write(4323,*) ';Preprocessor'
 write(4323,*) 'cpp			 = /lib/cpp'
 write(4323,*) ';Directories to include in the topology format'
 write(4323,*) 'include 		 = -I../top'
 write(4323,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(4323,*) 'integrator		 = md'
 write(4323,*) ';Total simulation time: 100 ps'
 write(4323,*) ':time step in femtoseconds'  
 write(4323,*) 'dt			 = 0.0005'
 write(4323,*) ';number of steps'
 write(4323,*) 'nsteps  		 = 2000'
 write(4323,*) ';frequency to write coordinates to output trajectory file'
 write(4323,*) 'nstxout 		 = 3000'
 write(4323,*) ';frequency to write velocities to output trajectory file'
 write(4323,*) 'nstvout 		 = 3000'
 write(4323,*) ';frequency to write energies to log file'
 write(4323,*) 'nstlog  		 = 3000'
 write(4323,*) ';frequency to write energies to energy file'
 write(4323,*) 'nstenergy		 = 200'
 write(4323,*) ';frequency to write coordinates to xtc trajectory' 
 write(4323,*) 'nstxtcout		 = 3000'
 write(4323,*) ';group(s) to write to xtc trajectory'
 write(4323,*) 'xtc_grps		 = protein CFP '  
 write(4323,*) 'group(s) to write to energy file' 
 write(4323,*) 'energygrps		 = protein sol CFP '
 write(4323,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(4323,*) ';when using twin-range cut-offs).' 
 write(4323,*) 'nstlist 		 = 10'
 write(4323,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(4323,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(4323,*) 'ns_type 		 = grid'
 write(4323,*) ';cut-off distance for the short-range neighbor list'
 write(4323,*) 'rlist		 = 1.4 '
 write(4323,*) ';treatment of electrostatic interactions'
 write(4323,*) 'coulombtype		 = pme'
 write(4323,*) 'pme_order            = 4'
 write(4323,*) 'fourierspacing       = 0.12' 
 write(4323,*) 'rcoulomb		 = 1.4' 
 write(4323,*) ';treatment of van der waals interactions'
 write(4323,*) 'rvdw			 = 1.4'
 write(4323,*) '; Periodic boudary conditions in all the directions' 
 write(4323,*) 'pbc                      = xyz'
 write(4323,*) ';Temperature coupling'
 write(4323,*) 'tcoupl  		 = berendsen'
 write(4323,*) 'tc-grps 		 = protein  CFP SOL NA+ GTP'   
 write(4323,*) 'tau_t	        = 0   0    0.1 0.1 0' 
 write(4323,*) 'ref_t		 = 300 300 100 100 100' 
 write(4323,*) ';Pressure coupling'
 write(4323,*) 'Pcoupl  		 = No'
 write(4323,*) 'Pcoupltype           = isotropic'
 write(4323,*) 'tau_p		 = 1.0'
 write(4323,*) 'compressibility 	 = 4.5e-5'
 write(4323,*) 'ref_p		 = 1.0'
 write(4323,*) ';Velocity generation'
 write(4323,*) 'gen_vel 		 = yes' 
 write(4323,*) 'gen_temp		 = 300'
 write(4323,*) 'gen_seed		 = 173529'
 write(4323,*) ';Constrain all bonds'
 write(4323,*) 'constraints		 = none'
 write(4323,*) ';freezegrps'
 write(4323,*) 'freezegrps               = protein CFP  GTP '
 write(4323,*) 'freezedim                = Y Y Y  Y Y Y  Y Y Y'

 close(unit=4323)

endif

if(dark_or_light == 1 .and. c11 == 'rac1' ) then

 open(unit=432,file='fullmd_sol.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(1x,a12,i7)') 'nsteps  		 =',md_time
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein FMNP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol FMNP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  FMNP SOL NA+ GTP'   
 write(432,*) 'tau_t	        = 0   0    0.1 0.1 0' 
 write(432,*) 'ref_t		 = 300 300 300 300 300' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=432,file='relax.mdp')

 write(432,*) 'title                    = MD simulation LOV2-Jalpha'

 write(432,*) ';Preprocessor'
 write(432,*) 'cpp			 = /lib/cpp'
 write(432,*) ';Directories to include in the topology format'
 write(432,*) 'include 		 = -I../top'
 write(432,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(432,*) 'integrator		 = md'
 write(432,*) ';Total simulation time: 100 ps'
 write(432,*) ':time step in femtoseconds'  
 write(432,*) 'dt			 = 0.001'
 write(432,*) ';number of steps'
 write(432,'(a28)') 'nsteps  		 = 300000'
 write(432,*) ';frequency to write coordinates to output trajectory file'
 write(432,*) 'nstxout 		 = 1500 '
 write(432,*) ';frequency to write velocities to output trajectory file'
 write(432,*) 'nstvout 		 = 1500 '
 write(432,*) ';frequency to write energies to log file'
 write(432,*) 'nstlog  		 = 1500 '
 write(432,*) ';frequency to write energies to energy file'
 write(432,*) 'nstenergy		 = 1500 '
 write(432,*) ';frequency to write coordinates to xtc trajectory' 
 write(432,*) 'nstxtcout		 = 1500 '
 write(432,*) ';group(s) to write to xtc trajectory'
 write(432,*) 'xtc_grps		 = protein FMNP '  
 write(432,*) 'group(s) to write to energy file' 
 write(432,*) 'energygrps		 = protein sol FMNP '
 write(432,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(432,*) ';when using twin-range cut-offs).' 
 write(432,*) 'nstlist 		 = 10'
 write(432,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(432,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(432,*) 'ns_type 		 = grid'
 write(432,*) ';cut-off distance for the short-range neighbor list'
 write(432,*) 'rlist		 = 1.4 '
 write(432,*) ';treatment of electrostatic interactions'
 write(432,*) 'coulombtype		 = pme'
 write(432,*) 'pme_order            = 4'
 write(432,*) 'fourierspacing       = 0.12' 
 write(432,*) 'rcoulomb		 = 1.4' 
 write(432,*) ';treatment of van der waals interactions'
 write(432,*) 'rvdw			 = 1.4'
 write(432,*) '; Periodic boudary conditions in all the directions' 
 write(432,*) 'pbc                      = xyz'
 write(432,*) ';Temperature coupling'
 write(432,*) 'tcoupl  		 = nose-hoover'
 write(432,*) 'tc-grps 		 = protein  FMNP SOL NA+ GTP'   
 write(432,*) 'tau_t	        = 0   0    0.1 0.1 0' 
 write(432,*) 'ref_t		 = 300 300 300 300 300' 
 write(432,*) ';Pressure coupling'
 write(432,*) 'Pcoupl  		 = Parrinello-Rahman'
 write(432,*) 'Pcoupltype           = isotropic'
 write(432,*) 'tau_p		 = 1.0'
 write(432,*) 'compressibility 	 = 4.5e-5'
 write(432,*) 'ref_p		 = 1.0'
 write(432,*) ';Velocity generation'
 write(432,*) 'gen_vel 		 = yes' 
 write(432,*) 'gen_temp		 = 300'
 write(432,*) 'gen_seed		 = 173529'
 write(432,*) ';Constrain all bonds'
 write(432,*) 'constraints		 = none'

 close(unit=432)

 open(unit=4323,file='fullmd_solequil.mdp')

 write(4323,*) 'title                    = MD simulation LOV2-Jalpha'

 write(4323,*) ';Preprocessor'
 write(4323,*) 'cpp			 = /lib/cpp'
 write(4323,*) ';Directories to include in the topology format'
 write(4323,*) 'include 		 = -I../top'
 write(4323,*) ';Run control: A leap-frog algorithm for integrating Newtons equations.' 
 write(4323,*) 'integrator		 = md'
 write(4323,*) ';Total simulation time: 100 ps'
 write(4323,*) ':time step in femtoseconds'  
 write(4323,*) 'dt			 = 0.0005'
 write(4323,*) ';number of steps'
 write(4323,*) 'nsteps  		 = 2000'
 write(4323,*) ';frequency to write coordinates to output trajectory file'
 write(4323,*) 'nstxout 		 = 3000'
 write(4323,*) ';frequency to write velocities to output trajectory file'
 write(4323,*) 'nstvout 		 = 3000'
 write(4323,*) ';frequency to write energies to log file'
 write(4323,*) 'nstlog  		 = 3000'
 write(4323,*) ';frequency to write energies to energy file'
 write(4323,*) 'nstenergy		 = 200'
 write(4323,*) ';frequency to write coordinates to xtc trajectory' 
 write(4323,*) 'nstxtcout		 = 3000'
 write(4323,*) ';group(s) to write to xtc trajectory'
 write(4323,*) 'xtc_grps		 = protein FMNP '  
 write(4323,*) 'group(s) to write to energy file' 
 write(4323,*) 'energygrps		 = protein sol FMNP '
 write(4323,*) ';Frequency to update the neighbor list (and the long-range forces,' 
 write(4323,*) ';when using twin-range cut-offs).' 
 write(4323,*) 'nstlist 		 = 10'
 write(4323,*) ';Make a grid in the box and only check atoms in neighboring grid cells'
 write(4323,*) ';when constructing a new neighbor list every nstlist steps.' 
 write(4323,*) 'ns_type 		 = grid'
 write(4323,*) ';cut-off distance for the short-range neighbor list'
 write(4323,*) 'rlist		 = 1.4 '
 write(4323,*) ';treatment of electrostatic interactions'
 write(4323,*) 'coulombtype		 = pme'
 write(4323,*) 'pme_order            = 4'
 write(4323,*) 'fourierspacing       = 0.12' 
 write(4323,*) 'rcoulomb		 = 1.4' 
 write(4323,*) ';treatment of van der waals interactions'
 write(4323,*) 'rvdw			 = 1.4'
 write(4323,*) '; Periodic boudary conditions in all the directions' 
 write(4323,*) 'pbc                      = xyz'
 write(4323,*) ';Temperature coupling'
 write(4323,*) 'tcoupl  		 = berendsen'
 write(4323,*) 'tc-grps 		 = protein  FMNP SOL NA+ GTP'   
 write(4323,*) 'tau_t	        = 0   0    0.1 0.1 0' 
 write(4323,*) 'ref_t		 = 300 300 100 100 100' 
 write(4323,*) ';Pressure coupling'
 write(4323,*) 'Pcoupl  		 = No'
 write(4323,*) 'Pcoupltype           = isotropic'
 write(4323,*) 'tau_p		 = 1.0'
 write(4323,*) 'compressibility 	 = 4.5e-5'
 write(4323,*) 'ref_p		 = 1.0'
 write(4323,*) ';Velocity generation'
 write(4323,*) 'gen_vel 		 = yes' 
 write(4323,*) 'gen_temp		 = 300'
 write(4323,*) 'gen_seed		 = 173529'
 write(4323,*) ';Constrain all bonds'
 write(4323,*) 'constraints		 = none'
 write(4323,*) ';freezegrps'
 write(4323,*) 'freezegrps               = protein FMNP GTP'
 write(4323,*) 'freezedim                = Y Y Y  Y Y Y  Y Y Y'

 close(unit=4323)

endif

end subroutine write_mdp
